spring:
  datasource:
    url: jdbc:h2:mem:ECOMMERCE;
    username: sa
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration